### ISSUE TITLE
seriously?

### ISSUE THREAD

**Issue by gimoh** [sindresorhus/root-check#1]
Oh man, I just can't believe this module exists, but anyway

Could you please at least add support for a variable like `I_KNOW_WTF_IM_DOING=true` and just skip?  And if the var is not set at the very least print some warning that you want to switch UID, just to avoid breaking the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

Thank you

**Comment by sindresorhus** [comment]
This is not the way to get your point across. I would have been happy to address your concerns if you had opened this in a more professional manner.
